# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b4a01e14e52e768f6345843f1e7f53bce8d16dd584f590b30d831171f520521da35d8473b0e8293f5086dd09de060d6ae4632395697074001c705b3b5a5c67e

test:
  secret_key_base: f46424c0f12cfdd570a8f57d0bfcfa59fdd41877d6d6dbc19ab5cac6b746ab5757d2be5d68d7fe080e045c791fb3a9e570d28d2431832b3b33ce272cc96f0024

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
